spring:
  datasource:
    url: jdbc:mysql://localhost:3306/othello?serverTimezone=UTC
    password: vaadin
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
ddl-auto: validate